[package]
name = "stamp-art"
version = "0.1.0"
authors = ["OJIMA Ryoji <rojima1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
panic = "abort"
codegen-units = 1
# lto = true

[dependencies]
